/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 T_shirt_gltf.zip.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/T_shirt_gltf.zip.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ribbing.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Ribbing_1.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Ribbing_2.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Ribbing_3.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Ribbing_4.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Ribbing_5.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Body_Front.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Body_Front_1.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Body_Front_2.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Body_Back.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Body_Back_1.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Body_Back_2.geometry} material={materials.Body_FRONT_2664} />
      <mesh geometry={nodes.Sleeves.geometry} material={materials.Sleeves_FRONT_2669} />
      <mesh geometry={nodes.Sleeves_1.geometry} material={materials.Sleeves_FRONT_2669} />
      <mesh geometry={nodes.Sleeves_2.geometry} material={materials.Sleeves_FRONT_2669} />
      <mesh geometry={nodes.Sleeves_3.geometry} material={materials.Sleeves_FRONT_2669} />
      <mesh geometry={nodes.Sleeves_4.geometry} material={materials.Sleeves_FRONT_2669} />
      <mesh geometry={nodes.Sleeves_5.geometry} material={materials.Sleeves_FRONT_2669} />
    </group>
  )
}

useGLTF.preload('/T_shirt_gltf.zip.gltf')
